### ISSUE TITLE
Colorize duplicate ports in the Ports Table section

### ISSUE THREAD

**Issue by JDea** [leovander/connect-stats#5]
Coloring the duplicate ports may create an easier method of identifying which channels have the same listening port values.

Example image showing duplicate ports

![image](https://user-images.githubusercontent.com/1392142/61901904-b9347280-aed5-11e9-96ef-4533781435cb.png)

**Comment by leovander** [comment]
@JDea I think the simplest solution might be either using an `Array` or `Object` to store the ports, and using either `_.find` or `_.findIndex` to see if that port is already being used by another channel. 

That would allow the current channel being looked at to add a flag that the port is duplicate/being used, but we would also have to store which channel is already using the port to back track in the channels and set its port as being duplicate. If that's the case we can use an `Object` to keep that relationship.

We need to make sure we only compare ports that do have actual [values/`HTTP/INTEROP/TCP/ETC`](https://github.com/leovander/connect-stats/blob/master/assets/js/main.js#L298), so we don't end up comparing blank strings like they are currently stored in the [channelObj](https://github.com/leovander/connect-stats/blob/master/assets/js/main.js#L293).

**Comment by leovander** [comment]
@JDea  Looking at it again, we can leverage the `activePorts` `Array` and potentially use the `_.findIndex`.
